---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "openfl.fullnameAggregator" . }}"
spec:
  selector:
    {{- include "openfl.selectorLabelsAggregator" . | nindent 4 }}
  ports:
    - name: agg-port
      port: {{ .Values.aggregatorPort }}
