---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "openfl.fullnameAggregator" . }}
  labels:
    {{- include "openfl.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "openfl.selectorLabelsAggregator" . | nindent 6 }}
  serviceName: "{{ include "openfl.fullnameAggregator" . }}"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openfl.selectorLabelsAggregator" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openfl.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{- range .Values.container.command }}
            - {{ . | quote }} {{- end }}
          args: {{- range .Values.container.args }}
            - {{ . | quote }} {{- end }}
          ports:
            - name: agg-port
              containerPort: {{ .Values.aggregatorPort }}
          resources:
            {{- toYaml .Values.resourcesAggregator | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
